### ISSUE TITLE
Einem anderen Nutzer eine Ich-denk-an-dich-Nachricht schicken

### ISSUE THREAD

**Issue by cc-cpo** [WirVsVirus-Virtuelle-Stimmungsringe/stimmungsringe_app#11]
Als angemeldeter Benutzer möchte ich in der Detailansicht einer anderen Person eine Nachricht auslösen können. Mehrfaches Auslösen wird unterbunden, bis die andere Person ihren Status ändert - dieser Zustand wird mit einem Text "bereits reagiert" unterhalb des Nachrichtentexts sowie dem Deaktivieren des Sende-Icons kenntlich gemacht.

Nachrichten werden auf dem Dashbord eines Benutzers mittels Herz-Symbol und der Anzahl an Nachrichten signalisiert. Das Herz wird augeblendet, wenn keine Nachrichten vorhanden sind.
Durch Click auf das Herz-Symbol öffnet sich eine neue Seite mit dem Text der Nachricht und dem Bild des Benutzers. Mehrere Nachrichten werden über Karoussel-Seite dargestellt

OOS: Push-Nachrichten (am Gerät)

**Comment by BendingBender** [comment]
hiho

**Comment by twinzz** [comment]
<img width="390" alt="Bildschirmfoto 2020-06-08 um 20 56 47" src="https://user-images.githubusercontent.com/7399485/84069289-98c8b600-a9ca-11ea-855c-6001c7147902.png">

**Comment by BendingBender** [comment]
![grafik](https://user-images.githubusercontent.com/4807083/84813370-6852ce80-afff-11ea-9d56-56d2461847d1.png)

**Comment by cc-cpo** [comment]
<img width="924" alt="Bildschirmfoto 2020-06-16 um 20 29 07" src="https://user-images.githubusercontent.com/1733410/84813464-4ada3080-b010-11ea-9705-044757246912.png">
