### ISSUE TITLE
App Icon einbauen

### ISSUE THREAD

**Issue by twinzz** [WirVsVirus-Virtuelle-Stimmungsringe/stimmungsringe_app#13]
Unser App icon anzeigen:

- [x] beim nächsten release auf dem Startbildschirm
- [x] im Slack-Channel

![android-chrome-256x256](https://user-images.githubusercontent.com/7399485/84068415-315e3680-a9c9-11ea-87d9-813c8411dfb6.png)

**Comment by BendingBender** [comment]
@twinzz Dani, ich brauche noch folgende Assets:

- [x] das icon in 1024x1024
- [x] nur das "F" als Vektorgrafik, idealerweise SVG + die Farbcodes für den Verlauf im Hintergrund (damit das Android-icon besser aussieht)

![grafik](https://user-images.githubusercontent.com/4807083/89213353-40c2c000-d5c5-11ea-8c2b-1f57e0fdd137.png)

**Comment by twinzz** [comment]
Links oben: 3C9A6B
rechts unten: #377371

**Comment by twinzz** [comment]
[F.svg.zip](https://github.com/WirVsVirus-Virtuelle-Stimmungsringe/stimmungsringe_app/files/5086628/F.svg.zip)
