### ISSUE TITLE
Layout Einstellungsscreen

### ISSUE THREAD

**Issue by twinzz** [WirVsVirus-Virtuelle-Stimmungsringe/stimmungsringe_app#17]
Wie soll die Seite Einsetllungen optisch aussehen?
- Gruppennamen anzeigen und ändern können
- Gruppe verlassen
- evtl nochmal Share Button?
- Gibt es eine "sind Sie sicher, dass Sie die Gruppe verlassen wollen?"

**Comment by twinzz** [comment]
![Screenshot_20200608-205928](https://user-images.githubusercontent.com/7399485/84069678-315f3600-a9cb-11ea-8554-698c7636d876.png)

**Comment by twinzz** [comment]
<img width="375" alt="Bildschirmfoto 2020-06-16 um 11 25 38" src="https://user-images.githubusercontent.com/7399485/84757212-2a848480-afc4-11ea-8d64-7a776f3331fc.png">

**Comment by twinzz** [comment]
- gruppe verlassen zu dominant
- Gleiche Share Layout wie bei Login
- drei Sektionen gestalten

**Comment by twinzz** [comment]
<img width="405" alt="Bildschirmfoto 2020-06-22 um 16 54 51" src="https://user-images.githubusercontent.com/7399485/85302223-274c3580-b4a9-11ea-9097-4bbf04205bc7.png">

**Comment by twinzz** [comment]
Muss ich da noch was machen?

**Comment by BendingBender** [comment]
Nö
