### ISSUE TITLE
Hoher Energieverbrauch im Hintergrund

### ISSUE THREAD

**Issue by cc-cpo** [WirVsVirus-Virtuelle-Stimmungsringe/stimmungsringe_app#19]
App wird mit hohem Verbrauch angezeigt

**Comment by BendingBender** [comment]
![Screenshot_20200607-135804_Device care](https://user-images.githubusercontent.com/4807083/84070547-d3772200-a9bb-11ea-949b-f735a885a7f0.jpg)

**Comment by BendingBender** [comment]
@cc-cpo Ist das immer noch so?
