### ISSUE TITLE
Hintergrundfarbe der Wetteranzeige überarbeiten

### ISSUE THREAD

**Issue by twinzz** [WirVsVirus-Virtuelle-Stimmungsringe/stimmungsringe_app#20]
Love It

**Comment by twinzz** [comment]
<img width="358" alt="Bildschirmfoto 2020-06-22 um 16 22 24" src="https://user-images.githubusercontent.com/7399485/85298814-d2a6bb80-b4a4-11ea-989e-4cc8b64f26e1.png">

**Comment by twinzz** [comment]
Zwischen Sonne und Nacht blau Grautöne ausprobieren

**Comment by twinzz** [comment]
<img width="1108" alt="Bildschirmfoto 2020-07-13 um 11 18 14" src="https://user-images.githubusercontent.com/7399485/87287786-cdb0b700-c4fa-11ea-9407-aa8971c3c4a7.png">
Jetzt nicht ganz so poppig bunt

**Comment by twinzz** [comment]
<img width="1108" alt="Bildschirmfoto 2020-07-13 um 13 56 30" src="https://user-images.githubusercontent.com/7399485/87301977-ceecde80-c510-11ea-8bb2-b5ce9de8d392.png">

**Comment by twinzz** [comment]
<img width="398" alt="Bildschirmfoto 2020-07-13 um 14 03 19" src="https://user-images.githubusercontent.com/7399485/87302425-ab766380-c511-11ea-8b1d-07d7cf01d6e8.png">

**Comment by twinzz** [comment]
<img width="310" alt="Bildschirmfoto 2020-07-13 um 20 19 06" src="https://user-images.githubusercontent.com/7399485/87338892-1fcafa00-c546-11ea-8d2c-e30201e68b5b.png">
In Poppig

**Comment by twinzz** [comment]
<img width="415" alt="Bildschirmfoto 2020-07-13 um 20 20 53" src="https://user-images.githubusercontent.com/7399485/87339098-615ba500-c546-11ea-841b-9ada6438d373.png">

**Comment by twinzz** [comment]
<img width="274" alt="Bildschirmfoto 2020-07-13 um 20 25 47" src="https://user-images.githubusercontent.com/7399485/87339617-2efe7780-c547-11ea-8318-5bc0c1659702.png">

**Comment by twinzz** [comment]
<img width="303" alt="Bildschirmfoto 2020-07-13 um 20 28 45" src="https://user-images.githubusercontent.com/7399485/87339850-7dac1180-c547-11ea-9b65-711b466b23ad.png">

**Comment by twinzz** [comment]
<img width="276" alt="Bildschirmfoto 2020-07-13 um 20 32 56" src="https://user-images.githubusercontent.com/7399485/87340210-10e54700-c548-11ea-8ae9-2c43173cb23e.png">
 Oder Hintergrund farbe immer die rechte farbe aus dem Verlauf

**Comment by twinzz** [comment]
<img width="752" alt="Bildschirmfoto 2020-07-13 um 20 35 11" src="https://user-images.githubusercontent.com/7399485/87340478-66b9ef00-c548-11ea-9ea2-709c6da53c0a.png">
Oder Hintergrund farbe immer die rechte farbe aus dem Verlauf

**Comment by twinzz** [comment]
Ich bin dafür die "bunten Varbverläufe" im nächsten Release zu nutzen. Idealerweise mit der wechselnden Hintergrundfarbe bei den Avataren.

**Comment by twinzz** [comment]
<img width="395" alt="Bildschirmfoto 2020-07-13 um 20 46 45" src="https://user-images.githubusercontent.com/7399485/87341505-07f57500-c54a-11ea-9981-94f669ea1000.png">

**Comment by twinzz** [comment]
https://xd.adobe.com/view/277fdfe9-cc51-49cf-96d3-f971a9f1cc07-722c/

**Comment by BendingBender** [comment]
@twinzz Dani, findest du das nicht zu krass bunt?
![grafik](https://user-images.githubusercontent.com/4807083/89129619-e5c69580-d4fe-11ea-95be-016208801608.png)

**Comment by twinzz** [comment]
Ich befürchte, dass es bunt/grell ist. Allerdings kann das auch ei Erkennungsmerkmal sein. Wir wollten es einfach mal eine Weile testen und ein gefühl dafür bekommen. 

Alternativ können wir den Hintergrund als Grauverlauf machen und lediglich die Wolke und die Avatarhintergrundfarbe geben über die Stimmung aufschluss? Können wir ja heute Abwend im Team abstimmen.

**Comment by twinzz** [comment]
<img width="521" alt="Bildschirmfoto 2020-08-17 um 13 03 46" src="https://user-images.githubusercontent.com/7399485/90389576-1fb0a380-e08a-11ea-8834-d28682df9484.png">

**Comment by twinzz** [comment]
<img width="311" alt="Bildschirmfoto 2020-08-17 um 13 41 00" src="https://user-images.githubusercontent.com/7399485/90392531-5806b080-e08f-11ea-908d-2207b6b31628.png">

**Comment by twinzz** [comment]
<img width="328" alt="Bildschirmfoto 2020-08-17 um 22 40 18" src="https://user-images.githubusercontent.com/7399485/90442297-bb6a0000-e0da-11ea-9dbe-df612a74d986.png">


So in der Art?

**Comment by twinzz** [comment]
<img width="273" alt="Bildschirmfoto 2020-08-17 um 23 18 40" src="https://user-images.githubusercontent.com/7399485/90445518-12be9f00-e0e0-11ea-8a0e-f8098d77a8ce.png">
 Da ist es wieder "mein Lila" :-)

**Comment by twinzz** [comment]
<img width="371" alt="Bildschirmfoto 2020-08-24 um 20 42 56" src="https://user-images.githubusercontent.com/7399485/91083342-6f730a00-e64a-11ea-8a13-5bce66d01baf.png">
