### ISSUE TITLE
Weitere Avatare gestalten

### ISSUE THREAD

**Issue by twinzz** [WirVsVirus-Virtuelle-Stimmungsringe/stimmungsringe_app#25]
Ich würde gerne mehr diversität bei den Avataren haben.
- Alt
- Jugendlich
- Robot
- Cat
- Flower
....

**Comment by twinzz** [comment]
![00_cat](https://user-images.githubusercontent.com/7399485/87301419-d8297b80-c50f-11ea-8c31-b7e0a7da8deb.png)
![00_panda](https://user-images.githubusercontent.com/7399485/87301427-dbbd0280-c50f-11ea-8848-b05e6e579fc2.png)
![00_robot](https://user-images.githubusercontent.com/7399485/87301433-dd86c600-c50f-11ea-8279-c04e3a063ec5.png)

**Comment by twinzz** [comment]
@BendingBender kannst Du die drei vllt scjhon mal einsetzen?

**Comment by twinzz** [comment]
![00_old_man](https://user-images.githubusercontent.com/7399485/91079502-68e19400-e644-11ea-99d0-b670eb660239.png)
![00-luise](https://user-images.githubusercontent.com/7399485/91079512-6c751b00-e644-11ea-8c96-8253fb988528.png)

**Comment by twinzz** [comment]
![00_dali](https://user-images.githubusercontent.com/7399485/91085573-f5dd1b00-e64d-11ea-8032-f66f5bab6e3b.png)

**Comment by twinzz** [comment]
![00_trump](https://user-images.githubusercontent.com/7399485/91088475-5c643800-e652-11ea-95cf-f751e8f55c55.png)

**Comment by twinzz** [comment]
![00_billie_eillish](https://user-images.githubusercontent.com/7399485/91090041-bf56ce80-e654-11ea-988d-1ee326fdc524.png)

**Comment by twinzz** [comment]
![00_superman](https://user-images.githubusercontent.com/7399485/91091832-7a806700-e657-11ea-8da5-9d99a1efb63d.png)

**Comment by cc-cpo** [comment]
added these constants: DUPERMAN, CYBERPUNK, GUY_FAWKES, GIRL_HUGE_HAIR, AGED_HIPSTER, ANXIOUS_ROBOT, PANDA_HEART, CAT_HEART
