### ISSUE TITLE
Anderes Icon-Set für die Wetter-Icons ausprobieren/eigene Icons machen

### ISSUE THREAD

**Issue by BendingBender** [WirVsVirus-Virtuelle-Stimmungsringe/stimmungsringe_app#26]
Wie findet ihr die:
http://www.alessioatzeni.com/portfolio/meteocons/

**Comment by twinzz** [comment]
<img width="1108" alt="Bildschirmfoto 2020-07-13 um 11 18 14" src="https://user-images.githubusercontent.com/7399485/87287615-99d59180-c4fa-11ea-950f-81e72c7e37f2.png">

hat einen Stil, den man nicht so oft sieht

**Comment by twinzz** [comment]
https://xd.adobe.com/view/277fdfe9-cc51-49cf-96d3-f971a9f1cc07-722c/

Die Hintergrundfarben sind jetzt bunt, siehe anderes Ticket
