### ISSUE TITLE
Screen "ich denk an Dich" (MessageViewPage) optimieren

### ISSUE THREAD

**Issue by twinzz** [WirVsVirus-Virtuelle-Stimmungsringe/stimmungsringe_app#30]
Name, Datum und evtl. auf welches Wetter jmd reagiert hat einbauen

**Comment by twinzz** [comment]
![Screenshot_20200831-115920](https://user-images.githubusercontent.com/7399485/91708731-062b5380-eb82-11ea-8cef-6f0852faba16.png)

**Comment by twinzz** [comment]
Mit den neuen Avataren wird es um so wichtiger den Namen anzuzeigen

**Comment by BendingBender** [comment]
@twinzz @cc-cpo @bleenow Was gefällt euch besser, bzw. habt ihr noch andere Vorschläge:

<img src="https://user-images.githubusercontent.com/4807083/103814250-a8dc6d00-5061-11eb-9b93-52c5f59903a8.png" width="400px" />
<img src="https://user-images.githubusercontent.com/4807083/103814340-c8739580-5061-11eb-803d-4709cd3c8d98.png" width="400px" />

**Comment by twinzz** [comment]
Mir gefällt der obere besser

**Comment by BendingBender** [comment]
@twinzz  @cc-cpo @bleenow So OK?

<img src="https://user-images.githubusercontent.com/4807083/103923351-48a70300-5115-11eb-8a71-cc88c636e898.png" width="400" />

**Comment by twinzz** [comment]
super
