### ISSUE TITLE
Optik für Darkmode fixen

### ISSUE THREAD

**Issue by cc-cpo** [WirVsVirus-Virtuelle-Stimmungsringe/stimmungsringe_app#35]

**Comment by BendingBender** [comment]
@twinzz wir brauchen hier hoch das gleiche Bild mit invertierten (oder so) Farben mit einem transparenten Hintergrund:
![grafik](https://user-images.githubusercontent.com/4807083/90431610-98832000-e0c9-11ea-9907-4d17570af3c4.png)

**Comment by twinzz** [comment]
<img width="305" alt="Bildschirmfoto 2020-08-17 um 22 54 30" src="https://user-images.githubusercontent.com/7399485/90443659-e48b9000-e0dc-11ea-9f52-8af358379d78.png">

**Comment by twinzz** [comment]
![familiarise_visual_black](https://user-images.githubusercontent.com/7399485/90443867-3502ed80-e0dd-11ea-8ee1-3cd181d1dccd.png)
![familiarise_visual_white](https://user-images.githubusercontent.com/7399485/90443872-37654780-e0dd-11ea-948c-57973e12075a.png)

**Comment by twinzz** [comment]
Ich hab die andere Gruppe genommen, die sich nicht so Stark an Familie asoziiert

**Comment by BendingBender** [comment]
@twinzz kannst du mir bitte das Bild für den dunklen Hintergrund mit transparentem Hintergrund anfertigen? Idealerweise das Bild für den hellen Hintergrund ebenfalls mit transparentem Hintergrund.

**Comment by twinzz** [comment]
![familiarise_logo_high-01](https://user-images.githubusercontent.com/7399485/91289344-86247880-e792-11ea-9487-a626e2b92a69.png)
![familiarise_logo_dark-01](https://user-images.githubusercontent.com/7399485/91289354-891f6900-e792-11ea-8cba-f0793cb0b7ba.png)
