### ISSUE TITLE
Check/improve caching of avatar images

### ISSUE THREAD

**Issue by cc-cpo** [WirVsVirus-Virtuelle-Stimmungsringe/stimmungsringe_app#38]
Endpoint de.wirvsvirus.hack.rest.AvatarController#getStockAvatar gets called whenever an avatar is rendered.

TODO: Investigate who to use NetworkImage or similar to adhere the caching headers from backend

**Comment by BendingBender** [comment]
Fixed in 0c2f1c7b125a36c1220390ff429584988025a8eb.
