### ISSUE TITLE
Avatarbilder ersetzen/neue einführen

### ISSUE THREAD

**Issue by BendingBender** [WirVsVirus-Virtuelle-Stimmungsringe/stimmungsringe_app#54]
Ideen:
- Frösche mit underschiedlicher Kleidung/Stimmung
- Abstraktere "Superhelden"

**Comment by twinzz** [comment]
Überlegung: Vllt müssen wir uns von den Avataren trennen? Wenn ich vom Push-Screen her überlege, könnte hier auch ein Symbol in Form von "Kaffeetasse, Kleeblatt, Blumenstraus, Hundewelpe, Daumen hoch ..." sein und wir gehen dann nur auf den NAmen.
Für die Profildarstellung könnte in dem Kreis das Wettersymbol prominenter erscheinen und rechts daneben Name und der später implementierte Kurztext "Warum gehts mir so bzw was tut mir gerade gut"?

**Comment by twinzz** [comment]
![00_trump](https://user-images.githubusercontent.com/7399485/134060221-3cdc2606-64ee-4ce9-9734-23c809a4cff9.png)
![00-boy-3](https://user-images.githubusercontent.com/7399485/134060244-e9265d6a-d004-4549-8888-1d4abbb1efac.png)
![00-builder](https://user-images.githubusercontent.com/7399485/134060258-05776a12-c453-401b-92f8-3523b7ee220a.png)
![00-woman-15](https://user-images.githubusercontent.com/7399485/134060268-d654fdf5-bb71-4c29-bfa7-43062b790795.png)

![00-woman-4](https://user-images.githubusercontent.com/7399485/134060278-5dacb9c9-6396-4b43-ba6b-4efd75689c73.png)
![00-man](https://user-images.githubusercontent.com/7399485/134060287-1dda3b3e-66db-4c2b-aad4-4c3d1a2fc06c.png)
