### ISSUE TITLE
Mock persönlicher Stimmungstext

### ISSUE THREAD

**Issue by twinzz** [WirVsVirus-Virtuelle-Stimmungsringe/stimmungsringe_app#60]
@Dani Rogge , könntest du mir vielleicht ein kleines Mock machen zum Thema wo ich persönlichen Stimmungstext anzeigen soll? Also in der Avatar Row? Oder nur auf der Page, wo man auf den Status eines Gruppenmitglieds reagieren kann?

**Comment by twinzz** [comment]
<img width="208" alt="Bildschirmfoto 2021-03-04 um 08 39 17" src="https://user-images.githubusercontent.com/7399485/109928001-42707580-7cc5-11eb-9360-6c4c37bd7ee5.png">
<img width="199" alt="Bildschirmfoto 2021-03-04 um 08 39 21" src="https://user-images.githubusercontent.com/7399485/109928007-443a3900-7cc5-11eb-9b00-fb324e7e7f8c.png">
<img width="203" alt="Bildschirmfoto 2021-03-04 um 08 39 43" src="https://user-images.githubusercontent.com/7399485/109928009-456b6600-7cc5-11eb-880e-3462d79a2f5d.png">
<img width="205" alt="Bildschirmfoto 2021-03-04 um 08 40 05" src="https://user-images.githubusercontent.com/7399485/109928012-4603fc80-7cc5-11eb-95a4-6e690e0c0097.png">

**Comment by twinzz** [comment]
@BendingBender habe hier schon mal die Mocks hochgeladen, die wir schon mal überlegt hatten.  Das simpelste wäre sicherich in der Memberansicht zwischen Avatarheader und den Grußnachrichten. 
Es gab aber auch eine Idee das in die Übersichtsseite zu integrieren, wenn die Texte wirklich sehr kurz sind oder  hier nur gekürzt angezeigt werden [...] und die Vollansicht dann wieder in der Memberansicht

**Comment by twinzz** [comment]
@BendingBender habe hier schon mal die Mocks hochgeladen, die wir schon mal überlegt hatten.  Das simpelste wäre sicherich in der Memberansicht zwischen Avatarheader und den Grußnachrichten. 
Es gab aber auch eine Idee das in die Übersichtsseite zu integrieren, wenn die Texte wirklich sehr kurz sind oder  hier nur gekürzt angezeigt werden [...] und die Vollansicht dann wieder in der Memberansicht

**Comment by twinzz** [comment]
![Bild von iOS](https://user-images.githubusercontent.com/7399485/110374418-f4ef6200-8050-11eb-8496-6f94864973fa.jpg)
Wir probieren mal Variante 1 aus. Eventuell kommt der Avatar wie das Herz rechts oben an den Kreis

**Comment by cc-cpo** [comment]
done
