### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by twinzz** [WirVsVirus-Virtuelle-Stimmungsringe/stimmungsringe_app#68]
Neu erstellen, dass es weniger Ähnlichkeit zu facebook gibt

**Comment by twinzz** [comment]
![fam_sun](https://user-images.githubusercontent.com/7399485/114447089-48b21580-9bd2-11eb-871f-bbed4b46680a.png)

Wie wäre es mit diesem Favicon?

**Comment by twinzz** [comment]
[Uploading favicon_package_v0.16.zip…]()

**Comment by twinzz** [comment]
SVG per Slack gepostet

**Comment by BendingBender** [comment]
nope, nichts angekommen bei slack

**Comment by twinzz** [comment]
Hatte es im Channel #produkt gepostet (hab jetzt gemerkt, da bist Du gar nicht drin )
