### ISSUE TITLE
Avatare als SVG

### ISSUE THREAD

**Issue by twinzz** [WirVsVirus-Virtuelle-Stimmungsringe/stimmungsringe_app#86]
Alle Avatare als transparente SVG bereitstellen

**Comment by twinzz** [comment]
![00_superman](https://user-images.githubusercontent.com/7399485/169882655-29b3bed3-900e-4232-9263-9773b47a2304.svg)
![00_billie_eillish](https://user-images.githubusercontent.com/7399485/169882692-d3d91cc3-aa50-4321-98e7-91baf5df785e.svg)
![00_trump](https://user-images.githubusercontent.com/7399485/169882699-23ec3e56-49ba-438f-bf65-f7e4b98e5200.svg)
![00_dali](https://user-images.githubusercontent.com/7399485/169882711-bea08386-a026-4b22-95e4-8466874eed94.svg)

![00_old_man](https://user-images.githubusercontent.com/7399485/169882739-ce808ea3-afe4-4b76-b274-517c5aae1ac6.svg)
![00-luise](https://user-images.githubusercontent.com/7399485/169882764-5e9dc6c0-5cd4-4020-83b8-4f97229d2be5.svg)
![00_miriam](https://user-images.githubusercontent.com/7399485/169882843-f85f22ab-645f-4c8c-ac6d-ac24b574634e.svg)

![00_dani](https://user-images.githubusercontent.com/7399485/169882839-2026921f-d407-49ec-a071-37e6612c097a.svg)
![00_dimi](https://user-images.githubusercontent.com/7399485/169882851-62bc0df0-75dc-4f09-b0af-b9e6c6cc04c9.svg)

![00_stefan](https://user-images.githubusercontent.com/7399485/169882858-c98abbca-a1b0-45f4-bd9d-96a801ac79ee.svg)



![00_cat](https://user-images.githubusercontent.com/7399485/169882783-40d608f5-92fa-4430-86d6-bf1a11b766c8.svg)
![00_robot](https://user-images.githubusercontent.com/7399485/169882790-174d2ec1-1492-4ff1-a820-72d688bb0ee1.svg)
![00_panda](https://user-images.githubusercontent.com/7399485/169882802-3273c2b3-5403-4964-bc66-b64113009849.svg)

![00_gudrun](https://user-images.githubusercontent.com/7399485/169882863-bcf29bc2-b3b2-4be1-a22f-d64651d03dd9.svg)
![00_lisa](https://user-images.githubusercontent.com/7399485/169882871-a9851c5c-2561-4095-a0ae-9790f79707d9.svg)

**Comment by twinzz** [comment]
![00-woman-15](https://user-images.githubusercontent.com/7399485/169882918-d99a2d7f-6178-4566-92f8-fb267e5e8f5c.svg)
![00-boy-3](https://user-images.githubusercontent.com/7399485/169883041-678c1aa1-2549-4a80-9534-c219d74f05a1.svg)
![00-builder](https://user-images.githubusercontent.com/7399485/169883049-b2d93e9e-22b3-495e-b87e-a3d98338bbea.svg)
![00-man-5](https://user-images.githubusercontent.com/7399485/169883076-02a291d7-3cb8-40c7-9186-c038725063e7.svg)
![00-man](https://user-images.githubusercontent.com/7399485/169883088-4cbf031c-ec28-4457-b7f0-e94828eb458d.svg)

**Comment by twinzz** [comment]
![015-woman-4](https://user-images.githubusercontent.com/7399485/169883507-9ba7b005-4c56-4a8d-b0d5-5e213266e0ef.svg)

**Comment by twinzz** [comment]
![pig](https://user-images.githubusercontent.com/7399485/169884322-ced19f7a-86b0-48fb-be52-6e47da1abed0.svg)

**Comment by twinzz** [comment]
![icebear](https://user-images.githubusercontent.com/7399485/169886079-b16e91e8-6c4e-4215-bfeb-214d5d0b7c17.svg)

**Comment by twinzz** [comment]
@BendingBender das sollten alle SVGs mit transparentem Hintergrund sein :-)

**Comment by BendingBender** [comment]
Danke!
